<?php
/**
 * SIMS — peta tabel dan kolom.
 * Berkas ini dibuat mengikuti skema aplikasi. Kolom bertanda json
 * disimpan sebagai teks JSON di dalam satu kolom.
 */

$SKEMA = [
  'pengguna' => ['kunci' => 'id', 'kolom' => ['id', 'nama', 'email', 'peran', 'jabatan', 'aktif', 'masuk', 'kontrak', 'kontrakAkhir', 'cutiJatah', 'salt', 'sandi', 'wajibGanti'], 'json' => []],
  'klien' => ['kunci' => 'id', 'kolom' => ['id', 'nama', 'alias', 'bentuk', 'npwp', 'group', 'prioritas', 'status', 'mulai', 'pic', 'kontak', 'email', 'drive', 'layanan', 'pkp', 'preparer', 'taxPic', 'supAwal', 'supAkhir', 'rev3', 'rev4', 'nilaiA', 'nilaiT', 'sumber', 'lengkap', 'onboard', 'portal', 'login', 'saltKlien', 'sandiKlien'], 'json' => ['layanan', 'onboard']],
  'project' => ['kunci' => 'id', 'kolom' => ['id', 'klien', 'jenis', 'pic', 'reviewer', 'mulai', 'status', 'nilai'], 'json' => []],
  'rekening' => ['kunci' => 'id', 'kolom' => ['id', 'klien', 'bank', 'no', 'mata', 'aktif'], 'json' => []],
  'kewajiban' => ['kunci' => 'id', 'kolom' => ['id', 'kode', 'nama', 'kategori', 'acuan', 'hari', 'akhirBulan', 'geser', 'dasar', 'perluSetor', 'aktif'], 'json' => []],
  'libur' => ['kunci' => 'id', 'kolom' => ['id', 'tgl', 'ket', 'tahun'], 'json' => []],
  'akun' => ['kunci' => 'id', 'kolom' => ['id', 'kode', 'nama', 'arah'], 'json' => []],
  'periode' => ['kunci' => 'id', 'kolom' => ['id', 'periode', 'kw', 'jtRaw', 'jt', 'verif', 'oleh', 'tglVerif', 'kunci'], 'json' => []],
  'patuh' => ['kunci' => 'id', 'kolom' => ['id', 'project', 'periode', 'kw', 'jt', 'billing', 'billingTgl', 'billingBukti', 'bayar', 'bayarTgl', 'bayarBukti', 'nominal', 'lapor', 'laporTgl', 'laporBukti', 'catatan'], 'json' => []],
  'produksi' => ['kunci' => 'id', 'kolom' => ['id', 'project', 'periode', 'tahap', 'diterima', 'batasAnalisa', 'batasLaporan', 'catatan'], 'json' => []],
  'analisa' => ['kunci' => 'id', 'kolom' => ['id', 'prod', 'rek', 'periode', 'batas', 'selesai', 'saldoAwal', 'saldoAkhir', 'masuk', 'keluar', 'kertas', 'status', 'pic', 'pos'], 'json' => ['pos']],
  'konfirm' => ['kunci' => 'id', 'kolom' => ['id', 'prod', 'item', 'saldo', 'tambah', 'link', 'status', 'tglKonfirm'], 'json' => []],
  'laporan' => ['kunci' => 'id', 'kolom' => ['id', 'prod', 'project', 'periode', 'batas', 'lr', 'nr', 'cf', 'mgmt', 'rekon', 'status', 'final'], 'json' => []],
  'review' => ['kunci' => 'id', 'kolom' => ['id', 'laporan', 'tahap', 'reviewer', 'fokus', 'batas', 'status', 'rumus', 'detail', 'catatan', 'tgl'], 'json' => []],
  'dokreq' => ['kunci' => 'id', 'kolom' => ['id', 'klien', 'project', 'siklus', 'periode', 'diminta', 'diterima', 'status', 'pic', 'jenis', 'drive'], 'json' => ['jenis']],
  'lm' => ['kunci' => 'id', 'kolom' => ['id', 'klien', 'periode', 'link', 'preparer', 'taxPic', 'supAwal', 'supAkhir', 'rev3', 'rev4', 'out', 'pajak', 'cek', 'deliverable', 'deliverTo', 'deliverBy', 'batasPajak', 'custom', 'kirim', 'umpan'], 'json' => ['out', 'pajak', 'cek']],
  'dokumen' => ['kunci' => 'id', 'kolom' => ['id', 'klien', 'periode', 'jenis', 'nama', 'link', 'oleh', 'tgl', 'catatan'], 'json' => []],
  'tugas' => ['kunci' => 'id', 'kolom' => ['id', 'judul', 'klien', 'project', 'siklus', 'pic', 'pihak', 'tenggat', 'status', 'catatan'], 'json' => []],
  'cuti' => ['kunci' => 'id', 'kolom' => ['id', 'tim', 'jenis', 'mulai', 'selesai', 'status', 'penyetuju', 'alasan'], 'json' => []],
  'meeting' => ['kunci' => 'id', 'kolom' => ['id', 'jenis', 'klien', 'tgl', 'jam', 'durasi', 'mode', 'link', 'lokasi', 'peserta', 'luar', 'gcal', 'gcalId', 'gcalLink', 'gcalStatus', 'gcalKirim', 'status', 'usul'], 'json' => ['peserta', 'luar']],
  'notulen' => ['kunci' => 'id', 'kolom' => ['id', 'meeting', 'ringkas', 'oleh', 'tgl', 'bagi'], 'json' => []],
  'aksi' => ['kunci' => 'id', 'kolom' => ['id', 'notulen', 'uraian', 'pic', 'tenggat', 'status', 'gcal'], 'json' => []],
  'pesan' => ['kunci' => 'id', 'kolom' => ['id', 'subjek', 'dari', 'ke', 'cc', 'keLuar', 'ccLuar', 'klien', 'klienAkses', 'pesan'], 'json' => ['ke', 'cc', 'keLuar', 'ccLuar', 'pesan']],
  'notif' => ['kunci' => 'id', 'kolom' => ['id', 'untuk', 'judul', 'teks', 'page', 'ref', 'tgl', 'jam', 'baca'], 'json' => ['untuk', 'baca']],
  'invoice' => ['kunci' => 'id', 'kolom' => ['id', 'no', 'klien', 'periode', 'nilai', 'ppn', 'total', 'terbit', 'kirim', 'jt', 'status', 'berkas'], 'json' => []],
  'bayar' => ['kunci' => 'id', 'kolom' => ['id', 'invoice', 'tgl', 'nominal', 'bukti', 'catatan'], 'json' => []],
  'lead' => ['kunci' => 'id', 'kolom' => ['id', 'nama', 'bidang', 'pic', 'kontak', 'sumber', 'pemilik', 'jasa', 'nilai', 'lingkup', 'tahap', 'penawaranTgl', 'followTgl', 'hasil', 'pks', 'nda', 'deal', 'alasan', 'followLagi', 'konversi'], 'json' => ['pks', 'nda']],
  'konten' => ['kunci' => 'id', 'kolom' => ['id', 'kanal', 'jenis', 'pilar', 'judul', 'pic', 'take', 'post', 'status', 'materi', 'tautan'], 'json' => []],
  'lampiran' => ['kunci' => 'id', 'kolom' => ['id', 'ref', 'nama', 'jenis', 'mime', 'ukuran', 'url', 'driveId', 'dok', 'oleh', 'tgl', 'status'], 'json' => []],
  'internal' => ['kunci' => 'id', 'kolom' => ['id', 'kelompok', 'nama', 'pic', 'supervisor', 'siklus', 'tenggat', 'status', 'catatan'], 'json' => []],
  'target' => ['kunci' => 'periode', 'kolom' => ['periode', 'laporan', 'pajak', 'catatan', 'oleh', 'tgl'], 'json' => []],
  'gcal' => ['kunci' => 'id', 'kolom' => ['id', 'judul', 'mulai', 'selesai', 'lokasi', 'tamu', 'dariSims'], 'json' => ['tamu']],
  'setelan' => ['kunci' => 'kunci', 'kolom' => ['kunci', 'nilai'], 'json' => []],
  'log' => ['kunci' => 'id', 'kolom' => ['id', 'tgl', 'oleh', 'aksi', 'ref', 'ip'], 'json' => []],
];

/* Nama koleksi di dashboard dipetakan ke nama tabel. */
$KOLEKSI = [
  'tim' => 'pengguna',
  'klien' => 'klien',
  'project' => 'project',
  'rekening' => 'rekening',
  'kewajiban' => 'kewajiban',
  'libur' => 'libur',
  'akun' => 'akun',
  'periode' => 'periode',
  'patuh' => 'patuh',
  'produksi' => 'produksi',
  'analisa' => 'analisa',
  'konfirm' => 'konfirm',
  'laporan' => 'laporan',
  'review' => 'review',
  'dokreq' => 'dokreq',
  'lm' => 'lm',
  'dok' => 'dokumen',
  'tugas' => 'tugas',
  'cuti' => 'cuti',
  'meeting' => 'meeting',
  'notulen' => 'notulen',
  'aksi' => 'aksi',
  'pesan' => 'pesan',
  'notif' => 'notif',
  'invoice' => 'invoice',
  'bayar' => 'bayar',
  'lead' => 'lead',
  'konten' => 'konten',
  'lampiran' => 'lampiran',
  'internal' => 'internal',
  'target' => 'target',
  'gcal' => 'gcal',
  'setelan' => 'setelan',
  'log' => 'log',
];

